# Stage 1: Build the binary
FROM golang:1.23.6 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o crawler ./cmd/crawler/main.go

# Stage 2: Build the Lambda container image using the official AWS Lambda Go base image
FROM public.ecr.aws/lambda/go:1

# Copy the binary into the Lambda image. Lambda looks for the binary in the directory defined by the LAMBDA_TASK_ROOT.
COPY --from=builder /app/crawler ${LAMBDA_TASK_ROOT}

# Set the command that Lambda will invoke - the binary name.
CMD [ "crawler" ]
